### ISSUE TITLE
Entities not syncing if "Disable Auto load Scene on Remotes" settings checkbox is marked

### ISSUE THREAD

**Issue by DanielSnd** [BoltEngine/Bolt-Tracker#113]
### How to reproduce issue
1. Under Bolt Settings -> Replication -> Tick the checkbox for "Disable Auto load Scene on Remotes"
2. Start a server
3. Spawn an entity on your server owned by your server.
4. Start a client, join the server.

### Expected Behavior
The client should be able to see the entity spawned by the server.

### Actual behavior
The client can't see the entity spawned by the server.

### Configuration
- Unity Version: 2018.2.21f
- Bolt Version: 1.2.7
- Operating System: Windows 10
- Network Configuration:

**Comment by ramonmelo** [comment]
Does all your game "run" in only one scene? Or, are you managing the scene loading manually?
Are the server and client in different scenes when this occurs?

**Comment by DanielSnd** [comment]
I reproduced the issue following the Bolt 101 getting started tutorial: https://doc.photonengine.com/en-us/bolt/current/demos-and-tutorials/bolt-basics/bolt-102-getting-started

In this case the game and menu are 2 different Scenes (Tutorial1 and Tutorial1_Menu).
Managing the scene loading manually with SceneManager.

**Comment by DanielSnd** [comment]
Unrelated but I've been trying to figure it out and haven't gotten an answer. Is there a way to access Photon Cloud's ClientState? I can't seem to get any reference to Photon Poller or Photon Cloud Global Callbacks

**Comment by ramonmelo** [comment]
Hello,

Bolt was architected to run on a server-client manner were all peers must be in the same game scene, so the entities can interact and be properly modified.

We've included the option to `Disable Auto load Scene on Remotes` as a request of one of our customers that needed difference approach when using Bolt, as his main goal was to use Bolt as kind of transport layer, sending and receiving raw data to sync the game state. Their setup was to control all scene loading by hand and the communication with the clients using the new [Binary Channel](https://doc.photonengine.com/en-us/bolt/current/dev-log/new-in-126#new-binary-channel).

Because of this, we consider this an advanced option and you need to know what you are doing and also be sure that you need such control.
