### ISSUE TITLE
SessionListUpdate not called if there is no server (1.2.9)

### ISSUE THREAD

**Issue by dushukai** [BoltEngine/Bolt-Tracker#132]
How to reproduce issue
Make sure there are no servers already started
BoltLauncher.StarClient()
Expected Behavior
SessionListUpdated callback shoud be fired. This way I can shutdown and start as server if there is none.
In 1.2.8 this callback is called

Actual behavior
The callback is only fired if any server creates a room

Configuration
Unity Version: 2018.3.0f2
Bolt Version: 1.2.9
Operating System: Windows
Network Configuration: Photon Cloud

**Comment by herpdederp** [comment]
This is working as intended. For example, before 1.2.9, if you’ve set the room list update to 5 seconds, you would need to wait for 5 seconds to received the callback. Then you will know that there are no session available. 
Now, you can just start a coroutine process when you’ve connected to wait the same 5 seconds.

**Comment by dushukai** [comment]
So 5 seconds is hard coded now? Is there any way to change it?

**Comment by herpdederp** [comment]
5 seconds is the default for room list update. You can change it in Bolt Settings.

**Comment by dushukai** [comment]
I mean I didn't see "room list update time" in 1.2.9, I have it in 1.2.8

**Comment by herpdederp** [comment]
In 1.2.9 it isn't in the Bolt Settings UI, you can modify these settings through code as shown here. https://github.com/BoltEngine/Bolt-Sample/blob/master/PhotonCloud/demo_simple/Scripts/PhotonInit.cs#L32

**Comment by dushukai** [comment]
Got it. Thanks. But I still have a question.
Wouldn't it not accurate if using coroutine to wait 5 seconds? Say if the player's network signal is bad, then the player may get the session list more than 5 seconds, however, due to the coroutine, the client will force shutdown and create a server. Won't this cause the the lobby has too many bad networking server which may provide a bad play experience to those clients connected?

**Comment by ramonmelo** [comment]
This behavior was changed on the latest version (1.2.9), from the changelog:

`**Changed**: Improved Session List update procedure. Now the callback SessionListUpdated is invoked when the session info changes, instead of on interval.`

If there is any server running when you start your game client, you will receive this callback _immediately_, and also when a new server is started, a server goes off or change properties.

This way, we support both "modes", you can call your `<Update UI Sessions method>`, for example, only when the session list changes (using the callback), or using a coroutine to check the `BoltNetwork.SessionList` on a regular basis (this would be the same behavior as invoking the callback on intervals, but we don't force you to use this way, like on older versions). 

The field on the Bolt Settings was removed, as it has no influence on the callback behavior.

You can take a look here with a minimal example of using the coroutine to restart the client when there is no server: [https://gist.github.com/ramonmelo/e0f1d8fb7e320af4d760e3e44c5a9dfc](url)
