### ISSUE TITLE
No null-check in BoltCore.BeginShutdown

### ISSUE THREAD

**Issue by ByvDeveloper** [BoltEngine/Bolt-Tracker#147]
**Describe the bug**
Got error: MissingReferenceException: The object of type '...' has been destroyed but you are still trying to access it.
Need add null-check for entity before force destroy;

** Stack **
BoltLog:Exception(Exception)
Bolt.Entity:Detach()
BoltCore:DestroyForce(Entity)
BoltCore:BeginShutdown(ControlCommandShutdown)
Bolt.ControlCommandShutdown:Run()
Bolt.ControlBehaviour:Update()

**Additional context**
- Unity Version: 2019.1.5f1
- Bolt Version: 1.2.9

**Comment by nlebedenco** [comment]
So 1.2.10 BoltCore.Detach() is apparently using an Assert but it's still a problem. Let's say for example that I have an object that like BoltPoll calls ShutdownImmediate in OnDestroy. Then I close my application or press stop in the editor.  Now because we can't control the order of destruction of game objects in unity (at least without resorting to tricks like explicit Script execution order) BoltEntity components may have been destroyed already by the time BoltCore.Detach is called. Best would be if Detach simply did nothing if passed a null entity.

**Comment by nlebedenco** [comment]
In fact, there is more to it than it seems. So I realized in my tests that the assertion was failing due to chaining of  detachment of some entities.  In other words, I was detaching an entity inside the Detached method of another entity and this poses a problem to ShutdownImmediate that calls destroy force on all entities in a loop expecting all to be properly attached.

**Comment by ramonmelo** [comment]
Thanks for your feedback!

Fixed on the next release.
