### ISSUE TITLE
GameDoesNotExist occured when BoltMatchmaking.JoinSession(string sessionID, IProtocolToken token) to join existing session

### ISSUE THREAD

**Issue by cetester001** [BoltEngine/Bolt-Tracker#153]
**Describe the bug**
- Occasionally, when calling BoltMatchmaking.JoinSession(string sessionID, IProtocolToken token) to join existing session, SessionConnectFailed will occur with error GameDoesNotExist.
- And the sessions list will be empty too in this scenario.
- But other clients can join this session successfully.
- If Shutdown and StartClient again, then it can get the sessions list and can join the session.
- There are 3 to 5 other sessions existed at the same time and each session has unique name.

**Additional context**
- Unity Version: 2019.2.12f1
- Bolt Version: 1.2.10
- Platform: Windows 10
- Network Configuration: Wifi

**Comment by ramonmelo** [comment]
Hello @cetester001 ,

I've been running some stress tests in order to reproduce your behavior, but I always get the list of sessions. Do you have a reproduction project? 

The Photon sessions are updated on the clients from time to time, and the synchronization may not be instantaneous, it can take a few seconds. So, after you create a session, it can take some time to get replicated across any client connected to the Lobby (state you enter when starts the client, but does not enter any room).

I'm using Bolt 1.2.11v and the attached sample [my_sample_test.unitypackage.zip](https://github.com/BoltEngine/Bolt-Tracker/files/4232695/my_sample_test.unitypackage.zip).
