### ISSUE TITLE
Bolt Release mode switch doesn't work

### ISSUE THREAD

**Issue by pippinmole** [BoltEngine/Bolt-Tracker#159]
### How to reproduce issue
1. Navigate to Bolt > Utils > Change DLL Mode (as Debug)
2. Wait for the process run through
3. Notice it doesn't change the DLL mode

### Expected Behavior
Should change to 'Release' mode

### Actual behavior
Stays at 'Debug' mode
https://gyazo.com/28a70b7d45e21ec95abfb3f5a1792e36

### Configuration
- Unity Version: 2019.3.3f1
- Bolt Version: v1.2.11a
- Operating System: Windows 10

**Comment by ramonmelo** [comment]
Hello @pippinmole ,

I was able to reproduce the described issue only if the current user does not have `write` permissions on the project's folder. Can you check if this is your case? 

Also, I've updated the editor script that executes the DLLs exchange in order to log the operations and give us a better idea of what can be happening in your case. 

You can download the new script [here](https://we.tl/t-4lhCVZ3VbH) and replace the file `Assets/Photon/PhotonBolt/editor/scripts/BoltUtils.cs`.
