### ISSUE TITLE
SceneLoadLocalDone called twice

### ISSUE THREAD

**Issue by vladnau89** [BoltEngine/Bolt-Tracker#174]
### How to reproduce issue
1. import sample package
2. add Level1 scene to BuildSettings from AdvancedTutorial folder 
3. run Bolt Compile 
4. open ServerCallbacks.cs from AdvancedTutorial  folder
5. change [BoltGlobalBehaviour(BoltNetworkModes.Server, "Level1")] to [BoltGlobalBehaviour(BoltNetworkModes.Server)]
6. add Debug.LogError("SceneLoadLocalDone scene : " + scene);  log to SceneLoadLocalDone method 
7. run Level1 scene from Bolt Debug Start by pressing Play Single Player
8. watch to console for SceneLoadLocalDone  log

### Expected Behavior
SceneLoadLocalDone  method called once as at previous version of bolt (1.2.12)

### Actual behavior
SceneLoadLocalDone method called twice

### Configuration
- Unity Version: 2019.3.15f1
- Bolt Version: 1.2.13
- Operating System: Win10

**Comment by ramonmelo** [comment]
Hello @vladnau89 ,

As stated on the Bolt Change Log page for v1.2.13:

`Changed: When you start Bolt, and there are GlobalListeners for the current scene, they will be loaded and receive events, which includes 'SceneLoadLocalDone', for example.`

This means, that when starting Bolt, if you have a `Bolt.GlobalEventListener` loaded, it will indeed receive the callback events. In your test case, this happens because you've removed the restriction to load the `ServerCallbacks` scripts only on the `Level1` scene, meaning that on every scene (which includes the `BoltDebugScene`) the `GlobalEventListener` will be loaded and invoke the callbacks.

You can avoid this by just passing the scene list you want the listener to work on or even use the same param as a regex pattern, loading it on any scenes that match a certain string pattern.

**Comment by vladnau89** [comment]
ok. Maybe this logic have reason for do that. but "scene" param for first calling SceneLoadLocalDone method can be different than  "scene" param for second calling. and it can be the same. steps for  scene = Level1 calling twice

1. add PhotonTutorial scene to BuildSettings as first scene. (index = 0)
2. run Bolt Complile
3. disable PhotonTutorial scene at BuildSettings window 
4. don`t change ServerCallbacks.cs . only add log for SceneLoadLocalDone  method
5. run Level1 as Play Single Player
6. SceneLoadLocalDone  with scene = Level1 will be calling twice 

it can be fixed by recomplile bolt. but at previous version of bolt it does not required 
My project is building with different scenes for dev and release build. Do I need to bolt recompile from build script now?

**Comment by ramonmelo** [comment]
Hello,

Yes, you always need recompile at every change to the Bolt Assets or Build Scenes, for example.
Bolt needs to be aware of the changes to work properly.

When you run the `Compile Assemblies`, Bolt will update the internal list of loaded scenes and work based on them, if you make a change and does not let Bolt consider them, we can't ensure the normal behavior.

Also, we recently fixed some issues towards the scene loading callbacks.
Are you using the latest version of Bolt? The released version is `1.2.13c`.

**Comment by vladnau89** [comment]
Hello, 
Yes, I am using 1.2.13c bolt version.
In our development pipeline it is a common use case : disable some scenes at BuildSettings and run build without bolt recompile. It`s work fine at previous version of bolt

**Comment by ramonmelo** [comment]
Hello @vladnau89 ,

> My project is building with different scenes for dev and release build.

In this case, you should always recompile Bolt, if you are changing the scene list. That is mandatory.

> In our development pipeline it is a common use case: disable some scenes at BuildSettings and run build without bolt recompile.

If you are running with the Debug Start, there is no need to disable the scenes, as it will load only your desired scene.
Also, if you loading other scenes based on the index, for example, we highly recommend to avoid this approach, but instead just include your scenes in the Build Settings, compile Bolt, and use the `BoltScenes` class to reference other scenes when loading them. This way you always have a solid reference to your scenes, even if you include or change their order.

In summary, what is happening:

You've included two scenes in the build, `Menu` (index 0) and `Level1` (index 1). When you Compile Bolt, it will store the information mapping each index with a specific scene.

Running with the `DebugStart`, the `BoltDebugScene` will be included at the end of the Build List (in this case, with index 2).
Bolt will load the debug scene and then load the target scene, in this case, Level1 (1). If you check the `BoltDebugStart.SceneLoadLocalDone` script callback, you will notice that it will be invoked two times, one for the starting done, other when the `Level1` is loaded, that is expected, and the `ServerCallbacks.SceneLoadLocalDone` will be invoked only once, for when the `Level1` is loaded.

Now, if you disable the scene `Menu` (0), all other scenes will be shifted by 1 index, meaning that `Level1` will now become 0, and `BoltDebugScene` to 1, on the Unity Scene List *only*. But, as you have not compiled Bolt, it still has stored that `Level1` at index 1.

When starting or changing scenes, Bolt will populate automatically the control loop with all `GlobalEventListeners` related to the target scenes (when starting, it uses the current scene index).
So, when the Bolt finishes the starting process, it will invoke the callbacks related to index 1 (the current scene: `BoltDebugScene` in the Build List), but looking at the stored information on `BoltScenes`, it refers to the old `Level1` at index 1 - keep in mind that this process occurs that way, not by mistake, Bolt uses the stored information about the scene indexes to communicate which scene must be loaded across the network, so it must be consistent with the Build list.
At this moment it will invoke both `BoltDebugStart.SceneLoadLocalDone` (because it has no target scene,) and the `ServerCallbacks.SceneLoadLocalDone` (because it targets `Level1`, with index 1 on the `BoltScenes`).
When the Debug Start scene asks to load the target scene (`Level1`), it will look again at the `BoltScenes` list for a valid reference, finding index 1, invoking the `ServerCallbacks.SceneLoadLocalDone` again.

In nutshell, to make sure you have consistent behavior, compile Bolt at every change.

--
Ramon Melo
Photon Bolt Team

**Comment by vladnau89** [comment]
I see. Thank you for the explanation! 

One more question : can I call Bolt Compile from script?

**Comment by ramonmelo** [comment]
Hello @vladnau89 ,

> One more question : can I call Bolt Compile from script?

Sure, here an example:

```csharp
using UnityEditor;
using UnityEngine;

public class MyCustomMenu
{
	[MenuItem("My Custom Menu/Run Custom Compiler")]
	public static void RunCustomCompiler()
	{
		Debug.LogWarning("Starting Custom Compiler");
		BoltMenuItems.RunCompiler();
		Debug.LogWarning("Custom Compiler Complete");
	}
}
```

**Comment by vladnau89** [comment]
Thank you!

**Comment by vladnau89** [comment]
Hello!
How about asset bundle pipeline? In our project all scenes (except first) are packed to asset bundle. Do I need Bolt compile after all scenes will be packed? Thank you
