### ISSUE TITLE
How to detect a disconnnected user in the updated Bolt Engine? Can you explain with examples?

### ISSUE THREAD

**Issue by yessGlory17** [BoltEngine/Bolt-Tracker#175]
How to detect a disconnnected user in the updated Bolt Engine? Can you explain with examples?

![unknown](https://user-images.githubusercontent.com/52113663/91580371-a9e3ec00-e955-11ea-87b4-6700360df89d.png)

Bolt Engine crashes when the user loses internet connection.

**Comment by ramonmelo** [comment]
Hello @yessGlory17 ,

Which Bolt version are you using? (the original issue template help us the know better your scenario from start)

By just adding this snippet to any `GlobalEventListener` that is currently running on the Scene, you should be able to catch the `Timeout` error and load the Scene with Index 0.
This works for both the client and the server;

```
public override void BoltShutdownBegin(AddCallback registerDoneCallback, UdpConnectionDisconnectReason disconnectReason)
{
    registerDoneCallback(() =>
    {
        Debug.LogFormat("Shutdown Done with Reason: {0}", disconnectReason);
        SceneManager.LoadScene(0);
    });
}
```

Which errors do you see? Can you send us the logs?

Also, in order to detect that a remote peer has disconnected just override the `Disconnected` on any `GlobalEventListener` on your scene:

```
public override void Disconnected(BoltConnection connection)
{
    Debug.LogFormat("{0} disconnected", connection.RemoteEndPoint);
}
```

--
Ramon Melo
Photon Bolt Team
