### ISSUE TITLE
Using BoltNetwork.RaycastAll allocates garbage

### ISSUE THREAD

**Issue by tfJonathan** [BoltEngine/Bolt-Tracker#176]
**Describe the bug**
Using BoltNetwork.RaycastAll allocates garbage.

**To Reproduce**
1 Create a new scene with a few Bolt hitbox bodies each having bolthitbox child components
(I used 16 bodies with each 24 hitboxes whereof some spheres and some boxes)

2 Create a new script named RaycastTest .cs and add:
```
using UnityEngine;
using Bolt.LagCompensation;

public class RaycastTest : MonoBehaviour
{
	private Ray[] _allRays;
	private const int RayCount = 100;

	private void Awake()
	{
		Random.InitState(1337);

		_allRays = new Ray[RayCount];
		for (int i = 0; i < RayCount; i++)
		{
			_allRays[i].direction = Random.insideUnitSphere;
		}
	}

	private void FixedUpdate()
	{
		for (int i = 0; i < RayCount; i++)
		{
			Ray ray = _allRays[i];
			BoltPhysicsHits hits = BoltNetwork.RaycastAll(ray, BoltNetwork.ServerFrame);
			for (int j = 0; j < hits.count; j++)
			{
				Debug.DrawRay(ray.origin, ray.direction * hits.GetHit(j).distance, Color.blue);
			}
		}
	}
}
```
3 Add script in the scene.

4 Press play and view results in the profiler.

**Expected behavior**
Garbage free raycasts similar to unity's Physics.Raycast or Physics.RaycastAllNonAlloc.
It would be great to have a BoltNetwork.RaycastAllNonAlloc in which I could pass a ref to a BoltPhysicsHit array that returns a hitcount.

**Actual behavior**
Garbage allocations similar to unity's Physics.RaycastAll.

**Screenshots**
![image](https://user-images.githubusercontent.com/60188130/95667176-bb2e3400-0b62-11eb-83a0-2bebb235438e.png)

**Desktop**
 - OS: Windows 10

**Additional context**
- Unity Version: 2018.4.24f1
- Bolt Version: v1.2.13c
- Network Configuration: Singleplayer / Server / Client

**Comment by tfJonathan** [comment]
After some digging in the dll I've found a possible cause of the garbage allocations.
In the method BoltHitbox.RaycastSphere a max value of scale gets calculated with 	
`Mathf.Max(scale.x, scale.y, scale.z)`. which under the hood creates a new array for each time it gets called.
Solution should be using` Mathf.Max(scale.x, Mathf.Max(scale.y, scale.z))` instead.

![image](https://user-images.githubusercontent.com/60188130/95763975-1a4d8f00-0cb0-11eb-8182-cfa84cbb5bba.png)

**Comment by ramonmelo** [comment]
Hello @tfJonathan ,

Thanks for your feedback.
We've improved the memory allocation on the Physics system based on your findings and other minor changes.

I just like to point out a small change in your script related to the usage of `BoltPhysicsHits` instances.
This class is a disposable type that uses an internal pooling system, so when dealing with them, we suggest that you make use of the `using` keyword ([link](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-statement)) so the reference is returned automatically to the pool, like is shown in the `Advanced Tutorial` ([link](https://github.com/BoltEngine/Bolt-Sample/blob/master/AdvancedTutorial/scripts/Weapon/WeaponRifle.cs#L23))

Instead of:

```csharp
private void FixedUpdate()
{
	for (int i = 0; i < RayCount; i++)
	{
		Ray ray = _allRays[i];
		BoltPhysicsHits hits = BoltNetwork.RaycastAll(ray, BoltNetwork.ServerFrame);
		for (int j = 0; j < hits.count; j++)
		{
			Debug.DrawRay(ray.origin, ray.direction * hits.GetHit(j).distance, Color.blue);
		}
	}
}
```

Use this way:

```csharp
private void FixedUpdate()
{
	for (int i = 0; i < RayCount; i++)
	{
		Ray ray = _allRays[i];
		using(BoltPhysicsHits hits = BoltNetwork.RaycastAll(ray, BoltNetwork.ServerFrame))
		{
			for (int j = 0; j < hits.count; j++)
			{
				Debug.DrawRay(ray.origin, ray.direction * hits.GetHit(j).distance, Color.blue);
			}
		}
	}
}
```

Just to illustrate the impact of the changes, I've performed some tests using the example you've described. 
Each test consisted of letting the application run and capture the memory allocation within a sequence of 300 frames on different random moments and average those values. For each test case described below, were performed 5 tests, represented by the bars on the graph.

Here are the results:

![chart](https://user-images.githubusercontent.com/873570/96269397-b2918f80-0fa0-11eb-8788-b7510a8d4223.png)

There is no error or missing data on the last test case (`Updated Code + Dispose`), we have just now a clean `alloc free` check.

The changes will be available on the next release.
