### ISSUE TITLE
Listening UDP socket is somehow left open and locked after shutdown

### ISSUE THREAD

**Issue by GetLitGames** [BoltEngine/Bolt-Tracker#180]
**Describe the bug**
During work on a simple Bolt game just getting started with the latest Bolt version, after several times building a Windows EXE and running it along with the Unity editor play mode, at some point one of them left the listening socket locked. Closed all copies of Unity, and of the Windows EXE - socket was still locked and somehow orphaned by the Windows EXE.

Running a new copy and trying to host a server gives the exception "Operation is not valid due to the current state of the object"

        var ip = GetLocalIPv4();
        BoltLauncher.StartServer(UdpKit.UdpEndPoint.Parse(ip + $":{21019}"));

12/20/2020 11:36:13 PM: System.InvalidOperationException: Operation is not valid due to the current state of the object.
  at UdpKit.Platform.DotNetSocket.VerifyIsBound () [0x0000f] in <bde927caff1548cb8cd9cc2013da1cfa>:0 
  at UdpKit.Platform.DotNetSocket.get_EndPoint () [0x00001] in <bde927caff1548cb8cd9cc2013da1cfa>:0 
  at UdpKit.Platform.PhotonSocket.Bind (UdpKit.UdpEndPoint ep) [0x0002a] in <c93d8eec51a640299148cd5edc2ff581>:0 
  at UdpKit.UdpSocket.CreatePhysicalSocket (UdpKit.UdpEndPoint ep, UdpKit.UdpSocketState s) [0x00039] in <5280815b43fd46cb847ed8beff08c77a>:0 
  at UdpKit.UdpSocket.OnEventStart (UdpKit.UdpEvent ev) [0x0001c] in <5280815b43fd46cb847ed8beff08c77a>:0 
  at UdpKit.UdpSocket.ProcessStartEvent () [0x0001a] in <5280815b43fd46cb847ed8beff08c77a>:0 
  at UdpKit.UdpSocket.NetworkLoop () [0x0000b] in <5280815b43fd46cb847ed8beff08c77a>:0 
UnityEngine.Debug:LogError(Object)
UnityWriter:BoltLog.IWriter.Error(String)
BoltLog:Error(String)
BoltInternal.BoltCore:UdpLogWriter(UInt32, String)
UdpKit.UdpLog:Write(UInt32, String)
UdpKit.UdpLog:Error(String, Object[])
UdpKit.UdpSocket:NetworkLoop()
UdpKit.Async.Task:Runner()
System.Threading.ThreadHelper:ThreadStart()

**To Reproduce**
Unknown steps to reproduce other than building Windows EXE, running as host and closing possibly with right click on taskbar and "Close" instead of the X in top right of window.

Closed all copies of Unity, and of the Windows EXE - socket was still locked.

At some point of doing this in a simple Bolt project after several runs, the socket was orphaned.

**Expected behavior**
Socket should always be released and available to listen on.

**Actual behavior**
Socket becomes orphaned and locked to a non-existent process somehow.

**Screenshots**
TCPVIEW shows the socket locked to a non-existent process. End Process does nothing. Process Properties says "unable to query <non-existent> process"
![image](https://user-images.githubusercontent.com/65694602/102740003-a61d1080-431c-11eb-9677-35105c80def0.png)

**Desktop (If applicable, please complete the following information):**
 - OS: Windows 10

**Additional context**
- Unity Version: 2019.4.4f1
- Bolt Version: 1.2.13c

**Comment by GetLitGames** [comment]
in Bolt 1.2.14a it seems to hang at BoltStartBegin and then when you hit stop button to stop playing in the editor, a few seconds later it says Operation is not valid due to the current state of the object.

**Comment by ramonmelo** [comment]
Hi @GetLitGames ,

> To Reproduce
> Unknown steps to reproduce other than building Windows EXE, running as host and closing possibly with right click on taskbar and "Close" instead of the X in top right of window.

You are asking to kill the application over and over, and expect that at some point, it will break.
That is not directly related to Bolt SDK, but how Windows OS handles a request like that.

The application creates threads and sockets to manage the connection, and those are being properly closed when the application follows the normal exit sequence, which is not the case if you just try to kill the application several times.

If the issue is not easily reproducible, it would be really hard to either fix it and properly test if the fix really does anything.

> in Bolt 1.2.14a it seems to hang at/after BoltStartBegin and then when you hit stop button to stop playing in the editor, a second or two later it says "Operation is not valid due to the current state of the object".

Does this happen using any of our Sample projects? After several tries, there is no hang or unresponsiveness during the normal operation of the Bolt flow, tested using SDK 1.2.14a on different Unity versions and the Gettings Started sample.
Do you have a project showing this behavior in a reproducible manner?
 
I've executed a test as you've described, and, although a see some orphan processes, they are cleared a few seconds later.
The test script runs an Unity standalone build that starts a Bolt Server on the same Port every time, right at the "Start" method, and kills it after a few seconds. This is done several times, always creating logs for each run.
No exceptions or problems with the startup process were found.

You can check the [script here](https://gist.github.com/ramonmelo/7bf422986903d60d201e291bced602f0).
