### ISSUE TITLE
Null reference on BoltCore.DisableLanBroadcast() after Bolt shutdown & restart on Connect

### ISSUE THREAD

**Issue by BassaForte** [BoltEngine/Bolt-Tracker#39]
###How to reproduce issue
1. Start bolt (BoltLauncher.StartClient)
2. Shutdown bolt (BoltLauncher.Shutdown)
3. Attempt to connect to a server

###Expected Behavior
The connection to the server should succeed (no error).

###Actual behavior
Null reference exception on BoltCore.DisableLanBroadcast() appears in the console, and server connection fails.

###Configuration
Unity Version: 5.6.1f1
Bolt Version: 1.0.0.5
Operating System: Windows 10 64bit

**Comment by fholm** [comment]
1. Start bolt (BoltLauncher.StartClient)
2. Shutdown bolt (BoltLauncher.Shutdown)
3. Attempt to connect to a server

I am not following these repro-steps, it says basically: start, shutdown, then connect - and the expected behavior is that it should succeed? Wouldn't the expected behavior be that it can't connect? since Bolt is shutdown.
